const EnglishLang ={
  "login_say_hello":"Say hello to your English tutors",
  "login_regist_say_hello":"Start learning with LetTutor",
  "login_description":"Become fluent faster through one on one video chat lessons tailored to your goals.",
  "login_regist_description":"Become fluent faster through one on one video chat lessons tailored to your goals.",
  "login_password":"Password",
  "login_forgot_pass":"Forgot Password?",
  "login_button":"LOG IN",
  "login_continue":"Or continue with",
  "login_not_member":"Not a member yet?",
  "login_already":"Already have an account?",
  "login_register":"Sign up",
  "login_login":"Log in",
  "login_confirm_password":"Confirm Password",
  "login_reset_password":"Reset Password",
  "login_reset_password_description":"Please enter your email address to search for your account.",
  "login_reset_password_sent_description":"Check your inbox for a link to reset your password.",
  "login_reset_password_sent_back":"Return Log In Page",
  "login_reset_password_submit":"Send reset link",

};

const VietnameseLang ={
  "login_say_hello":"Nói xin chào với gia sư tiếng Anh của bạn",
  "login_regist_say_hello":"Đăng ký",
  "login_description":"Trở nên thông thạo nhanh hơn thông qua các bài học trò chuyện video trực tiếp phù hợp với mục tiêu của bạn.",
  "login_regist_description":"Phát triển kỹ năng tiếng Anh nhanh nhất bằng cách học 1 kèm 1 trực tuyến theo mục tiêu và lộ trình dành cho riêng bạn.",
  "login_password":"Mật Khẩu",
  "login_forgot_pass":"Quên Mật Khẩu?",
  "login_button":"ĐĂNG NHẬP",
  "login_continue":"Hoặc tiếp tục với",
  "login_not_member":"Hiện tại chưa là thành viên?",
  "login_register":"Đăng ký",
  "login_already":"Đã có tài khoản?",
  "login_login":"Đăng nhập",
  "login_confirm_password":"Nhập lại mật khẩu",
  "login_reset_password":"Đặt lại mật khẩu",
  "login_reset_password_description":"Vui lòng nhập email để tìm kiếm tài khoản của bạn.",
  "login_reset_password_sent_description":"Kiểm tra hộp thư đến trong email để đặt lại mật khẩu của bạn.",
  "login_reset_password_sent_back":"Trở về trang đăng nhập",
  "login_reset_password_submit":"Xác nhận",
};